# Generated by Django 5.0.4 on 2024-04-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_status_user_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/blog/media/post', upload_to='post/'),
            preserve_default=False,
        ),
    ]
